---
- name: Create isucon group
  become: yes
  become_user: root
  group:
    name: isucon
    gid: 1005
    state: present
    system: no

- name: Create isucon user
  become: yes
  become_user: root
  user:
    name: isucon
    uid: 1005
    group: isucon
    password: isucon
    home: /home/isucon
    shell: /bin/bash
    state: present
    system: no

- name: Add sudoers
  become: yes
  become_user: root
  lineinfile:
    line: "isucon  ALL=(ALL) NOPASSWD:ALL"
    dest: /etc/sudoers
    state: present
    owner: root
    group: root
    mode: 0440

- name: Install packages
  become: yes
  become_user: root
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - autoconf
    - automake
    - curl
    - dstat
    - libgdbm-dev
    - git
    - jq
    - libffi-dev
    - libyaml-dev
    - libncurses5-dev
    - libssl-dev
    - patch
    - libreadline-dev
    - sudo
    - zlib1g-dev

- name: Install xbuild
  become: yes
  become_user: isucon
  git:
    repo: https://github.com/tagomoris/xbuild.git
    dest: /home/isucon/xbuild
    version: master

- name: mkdir /home/isucon/local for xbuild
  become: yes
  become_user: isucon
  file:
    path=/home/isucon/local
    state=directory
