---
- name: Put nginx.conf
  become: yes
  become_user: root
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Put isucon.conf
  become: yes
  become_user: root
  copy:
    src: isucon.conf
    dest: /etc/nginx/conf.d/isucon.conf

- name: Restart nginx
  become: yes
  become_user: root
  service:
    name: nginx
    state: restarted

- name: Put torb.nodejs.service
  become: yes
  become_user: root
  copy:
    src: torb.nodejs.service
    dest: /etc/systemd/system/torb.nodejs.service

- name: Put torb.go.service
  become: yes
  become_user: root
  copy:
    src: torb.go.service
    dest: /etc/systemd/system/torb.go.service

- name: Put torb.python.service
  become: yes
  become_user: root
  copy:
    src: torb.python.service
    dest: /etc/systemd/system/torb.python.service

- name: Put torb.ruby.service
  become: yes
  become_user: root
  copy:
    src: torb.ruby.service
    dest: /etc/systemd/system/torb.ruby.service

- name: Install for torb.nodejs
  become: yes
  become_user: isucon
  args:
    chdir: /home/isucon/torb/webapp/nodejs
  shell: |
    bash -lc "/home/isucon/local/node/bin/npm install"

- name: Install for torb.go
  become: yes
  become_user: isucon
  args:
    chdir: /home/isucon/torb/webapp/go
  shell: |
    bash -lc "make clean && make deps && make"

- name: Install for torb.python
  become: yes
  become_user: isucon
  args:
    chdir: /home/isucon/torb/webapp/python
  shell: |
    bash -lc "sh setup.sh"

# - name: Install for torb.ruby
#   become: yes
#   become_user: isucon
#   args:
#     chdir: /home/isucon/torb/webapp/ruby
#   shell: |
#     bash -lc "bundle install --path=.bundle"
