---
- name: Add user nginx
  user:
    name: nginx

- name: Install nginx
  apt:
    name: nginx
    state: latest
    update_cache: yes
    cache_valid_time: 3600

- name: service nginx start
  service:
    name: nginx
    enabled: yes

