---
- hosts: bench
  roles:
    - common
    - increase_ulimit
    - install_go
    - deploy_webapp
    - deploy_bench
    - build_bench
    - deploy_bench_binary
    # - prepare_bench
    # - start_bench_worker
